workflows:
  build_pdfmaster:
    name: PDFMaster Build
    environment:
      flutter: stable
      xcode: latest
      android_signing:
        - keystore_reference: keystore
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf pubspec.lock

      - name: Install dependencies
        script: |
          flutter pub get
          flutter pub upgrade --major-versions

      - name: Analyze and test
        script: |
          flutter analyze
          flutter test || true

      - name: Build release APK
        script: |
          flutter build apk --release --no-tree-shake-icons

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - vikascoading@gmail.com
